def swapFiles(path1,path2):
    openFile1=open(path1,'r')
    openFile2=open(path2,'r')
    file1data=openFile1.read()
    file2data=openFile2.read()
    openFile1.close()
    openFile2.close()
    openFile1=open(path1,'w')
    openFile2=open(path2,'w')
    openFile2.write(str(file1data))
    openFile1.write(str(file2data))
    openFile1.close()
    openFile2.close()
    print('Files Swapped')
swapFiles('sample1.txt','sample2.txt')